<?php
declare(strict_types=1);

if (!isset($_SESSION['id_usuario'])) {
  header('Location: /?view=login');
  exit;
}
?>
<!DOCTYPE html>
<html lang="es">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Reservar una Mesa — El Arca</title>
  <link rel="stylesheet" href="/assets/css/styles.css?v=2025-01">
  <link
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
    rel="stylesheet" />
</head>

<body class="auth-page">

  <?php require __DIR__ . '/partials/navbar.php'; ?>

  <!-- Use auth-bg or app-container, here using main container for scrolling booking flow -->
  <main class="app-container" style="padding-bottom: 6rem;">

    <div class="section-header" style="margin-top: 2rem;">
      <h2 class="text-glow">Reservar una Mesa</h2>
      <p>Elige tu lugar ideal rodeado de naturaleza.</p>
    </div>

    <form method="POST" action="/?action=realizar_reserva" id="bookingForm"
      style="max-width: 600px; margin: 0 auto; padding: 0 1.5rem;">

      <!-- 1. CUÁNDO (Calendar) -->
      <h3 style="color: white; font-size: 1.1rem; margin-bottom: 1rem;">Cuándo</h3>

      <div class="calendar-container">
        <div class="calendar-header">
          <button type="button" class="btn-circle" id="prevMonth"><span
              class="material-symbols-outlined">chevron_left</span></button>
          <span style="color: white; font-weight: 700;" id="currentMonthLabel">Enero 2024</span>
          <button type="button" class="btn-circle" id="nextMonth"><span
              class="material-symbols-outlined">chevron_right</span></button>
        </div>

        <div class="calendar-grid">
          <span class="calendar-day-label">D</span>
          <span class="calendar-day-label">L</span>
          <span class="calendar-day-label">M</span>
          <span class="calendar-day-label">M</span>
          <span class="calendar-day-label">J</span>
          <span class="calendar-day-label">V</span>
          <span class="calendar-day-label">S</span>
          <!-- Valid days generated by JS -->
          <div id="calendarDays" style="display: contents;"></div>
        </div>
      </div>

      <!-- Hidden Input for Date -->
      <input type="hidden" name="fecha" id="fechaInput" required>

      <!-- 2. HORARIO (Time Chips) -->
      <h3 style="color: white; font-size: 1.1rem; margin-bottom: 1rem;">Horario</h3>
      <div class="time-chips-container" id="timeSlots">
        <!-- Generated by JS based on date -->
        <div style="padding: 1rem; color: var(--text-muted); font-size: 0.9rem;">Selecciona una fecha primero</div>
      </div>
      <input type="hidden" name="hora" id="horaInput" required>

      <!-- 3. PERSONAS (Counter) -->
      <h3 style="color: white; font-size: 1.1rem; margin: 1.5rem 0 1rem;">Número de Personas</h3>
      <div class="guest-counter">
        <div style="display: flex; align-items: center; gap: 0.5rem;">
          <span class="material-symbols-outlined" style="color: var(--primary);">groups</span>
          <span style="color: white; font-weight: 700;" id="guestLabel">4 Personas</span>
        </div>

        <div style="display: flex; align-items: center; gap: 1rem;">
          <button type="button" class="btn-circle" id="decreaseGuests">
            <span class="material-symbols-outlined">remove</span>
          </button>
          <span style="color: white; font-weight: 700; width: 20px; text-align: center;" id="guestCount">4</span>
          <button type="button" class="btn-circle" id="increaseGuests">
            <span class="material-symbols-outlined">add</span>
          </button>
        </div>
      </div>
      <input type="hidden" name="personas" id="personasInput" value="4">

      <!-- 4. DÓNDE (Area Cards) -->
      <h3 style="color: white; font-size: 1.1rem; margin: 1.5rem 0 1rem;">Área del Restaurante</h3>

      <label class="area-card" onclick="selectArea('jardin')">
        <div class="area-icon"><span class="material-symbols-outlined">park</span></div>
        <div style="flex: 1;">
          <h4 style="color: white; font-weight: 700; font-size: 1rem;">Jardín Exterior</h4>
          <p style="color: var(--text-muted); font-size: 0.8rem;">Rodeado de árboles y aire fresco.</p>
        </div>
        <div class="area-radio">
          <div class="area-radio-inner"></div>
        </div>
        <input type="radio" name="zona" value="Jardín" style="display: none;" id="radio_jardin">
      </label>

      <label class="area-card" onclick="selectArea('salon')">
        <div class="area-icon"><span class="material-symbols-outlined">restaurant</span></div>
        <div style="flex: 1;">
          <h4 style="color: white; font-weight: 700; font-size: 1rem;">Salón Principal</h4>
          <p style="color: var(--text-muted); font-size: 0.8rem;">Ambiente premium y climatizado.</p>
        </div>
        <div class="area-radio">
          <div class="area-radio-inner"></div>
        </div>
        <input type="radio" name="zona" value="Salón" style="display: none;" id="radio_salon">
      </label>

      <label class="area-card" onclick="selectArea('juegos')">
        <div class="area-icon"><span class="material-symbols-outlined">sports_esports</span></div>
        <div style="flex: 1;">
          <h4 style="color: white; font-weight: 700; font-size: 1rem;">Zona de Juegos</h4>
          <p style="color: var(--text-muted); font-size: 0.8rem;">Ideal para familias con niños.</p>
        </div>
        <div class="area-radio">
          <div class="area-radio-inner"></div>
        </div>
        <input type="radio" name="zona" value="Juegos" style="display: none;" id="radio_juegos">
      </label>

      <!-- 5. NOTES -->
      <h3 style="color: white; font-size: 1.1rem; margin: 1.5rem 0 1rem;">Notas Adicionales</h3>
      <textarea name="notas" class="notes-area" placeholder="¿Alguna alergia o requerimiento especial?"></textarea>

      <!-- SUBMIT -->
      <button type="submit" class="btn btn-premium" style="width: 100%; margin-top: 2rem;">
        <span class="text">Confirmar Reservación</span>
        <span class="material-symbols-outlined">check_circle</span>
      </button>

    </form>
  </main>

  <nav class="bottom-nav">
    <a href="/?view=home" class="nav-item">
      <span class="material-symbols-outlined">home</span>
      <span>Inicio</span>
    </a>
    <a href="/?view=menu" class="nav-item">
      <span class="material-symbols-outlined">menu_book</span>
      <span>Menú</span>
    </a>
    <a href="/?view=galeria" class="nav-item">
      <span class="material-symbols-outlined">gallery_thumbnail</span>
      <span>Galería</span>
    </a>
    <a href="/?view=reservaciones" class="nav-item active">
      <span class="material-symbols-outlined">calendar_today</span>
      <span>Reservas</span>
    </a>
  </nav>

  <script src="/assets/js/mobile-enhancements.js"></script>
  <script>
    // --- Booking Logic ---
    function selectArea(id) {
      document.querySelectorAll('.area-card').forEach(el => el.classList.remove('active'));
      // Find the card containing the clicked radio and make it active
      const radio = document.getElementById('radio_' + id);
      radio.checked = true;
      radio.closest('.area-card').classList.add('active');
    }

    document.addEventListener('DOMContentLoaded', () => {
      // --- 1. Calendar Generation (Simplified for Demo) ---
      const calendarGrid = document.getElementById('calendarDays');
      const monthLabel = document.getElementById('currentMonthLabel');
      const dateInput = document.getElementById('fechaInput');
      const timeContainer = document.getElementById('timeSlots');
      const timeInput = document.getElementById('horaInput');

      const now = new Date();
      const currentMonth = now.toLocaleString('es-ES', { month: 'long', year: 'numeric' });
      monthLabel.textContent = currentMonth.charAt(0).toUpperCase() + currentMonth.slice(1);

      // Generate dummy days for current month view
      const daysInMonth = new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate();

      // Simple offset for starting day (just for visual structure)
      for (let i = 0; i < now.getDay(); i++) {
        const empty = document.createElement('div');
        calendarGrid.appendChild(empty);
      }

      for (let i = 1; i <= daysInMonth; i++) {
        const dayEl = document.createElement('div');
        dayEl.className = 'calendar-day';
        dayEl.textContent = i;

        // Disable past days
        if (i < now.getDate()) {
          dayEl.style.opacity = '0.3';
          dayEl.style.cursor = 'default';
        } else {
          dayEl.addEventListener('click', () => {
            document.querySelectorAll('.calendar-day').forEach(d => d.classList.remove('active'));
            dayEl.classList.add('active');

            // Set Date Value (YYYY-MM-DD)
            const yyyy = now.getFullYear();
            const mm = String(now.getMonth() + 1).padStart(2, '0');
            const dd = String(i).padStart(2, '0');
            dateInput.value = `${yyyy}-${mm}-${dd}`;

            // Generate Hours
            generateHours();
          });
        }
        calendarGrid.appendChild(dayEl);
      }

      function generateHours() {
        timeContainer.innerHTML = '';
        const hours = ['12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00', '19:00', '20:00', '21:00'];

        hours.forEach(time => {
          const chip = document.createElement('div');
          chip.className = 'time-chip';
          chip.textContent = time;
          chip.addEventListener('click', () => {
            document.querySelectorAll('.time-chip').forEach(c => c.classList.remove('active'));
            chip.classList.add('active');
            timeInput.value = time;
          });
          timeContainer.appendChild(chip);
        });
      }


      // --- 2. Guest Counter ---
      let count = 4;
      const countEl = document.getElementById('guestCount');
      const labelEl = document.getElementById('guestLabel');
      const inputEl = document.getElementById('personasInput');

      document.getElementById('decreaseGuests').addEventListener('click', () => {
        if (count > 1) {
          count--;
          updateGuests();
        }
      });

      document.getElementById('increaseGuests').addEventListener('click', () => {
        if (count < 20) {
          count++;
          updateGuests();
        }
      });

      function updateGuests() {
        countEl.textContent = count;
        labelEl.textContent = count + ' Personas';
        inputEl.value = count;
      }
    });
  </script>
</body>

</html>